language: cpp

env:
  global:
    - secure: "YHWvVlx5wv2POltS4EfKtbI9PH0NKzv/ud1tNeFn7Zga5bi40jJ1Uqi1n+NfHYmIfhuTNh72VnVkieCcu9q2CSsbVArRAO8GTi82UD+MW+h4Pc4UjdqZVcD4DeY7txQKrrgtbG3qoEm4wT4wm3wAIgbi4uh/unGky7XrSSsVRyK4iR3KEn/WENMp+GcqVgv3d12A3diqq54HDaC9vSAKr3f0htYtuYKWbgQ2O6sBwZUph62S13nYumQAoCd+qEL/E11LH1ID/5xkXYF1ZbRYo/ojIZvgKP6mTq65ErJ2pgI5Sw+wtFYYyGWnLbZGFupqe5F0pRz9Tofbmj2HErkybXrb2CTAnuwM5s8ZGqEhga0Mdm7hx2kgBGOvj+ed34s7730cEd8vGdsZwgs+hZlLrs6g6uMnzKmCnpD9VgWKzuHWFrR6OxYnBUJ3CxTswgoChBqDcI7OvEj0Nj9cZ9F9x+i1QFefqU0uxho26y2A37Y8NszzwpOyT9oo4Zquzq2Dk6vzL9Eo/pK7XCTiYDD77EWYGAo1tU5xfkfZOxpOXbuWL38Cu4YosvfgUtoS5hzyEjxuGbVkAAqeK8OU6BumMVbUDvT0HNxku003aW3rzqhxeu0ERCUU5kAJJQkp/E274TRj63xjWH6HCjVsIHBf9AirqFttV0X/b0Lo21zGxR8="
    - OBS_USER=metaxy

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          env: SPEC=linux-g++-64 CONFIG=installer
          sudo: required
          before_install: . travis/linux-install.sh
          script:  . travis/linux-script.sh
          deploy:
            provider: bintray
            file: "bintray/linux.json"
            user: "metaxy"
            on:
                branch: master
            key:
                secure: "oavrVI8xdXD1h0xmDMNfQjSlN270glnmQ4gXvN9JocxSkg4KpUPX6fe90xKo+zKVLWtJhncdIzxmSq5VQ1aV/SdJEjasrel6QfvMn3xJVgTh3fQkIgu29QXii0CV9l30TMsrIhjYDkrbGnesulXG/D+QvLdB1xnD/zcsOvZxv3NA/q8gzb8rwPoMrOeWtnzlFUVgm2OKAtYTmyS7GlEnaztXQEsN3l4hViurTV9pFrpS28Ly1IYnOgqahMDHE1YqjRoK+/8+TbmrBQyacZWAXCsD8nnUWKQ364BdGUYZvF653L4a0SRUr1Y5vy0rQktjguhV1duyvcGV42KADAA6lR7C4EaeLDOydA1cuTQaKpmokFIJ6+1L6TtzIqBOjcaNzDGJsvpc8yoaxl0cqx5AKyhRKMvBeuw4nr9y0py4QjBqXmdion547VSD4/coJtMDhtdC8GetO7GkuMwWn2xOwHLdw6X205R+C9D9ePl4gl2CNa7OJUNYZoW7jMhfut08F/rcdeNSW3mNN9Zb2NACZ9+O6vHhzXc92Y0cYNTN32wizbI/+xpLY88aAM4kTpUEVhHzPkDHtCJzTeHTG3BfZuKVedVZjM/sdF9W3zDgkOjtfoyW8+bMJNJ9AKSLQWOWRq/rnVpylPrF9ITForg72W2u0Mh9Gd6/MuvgAlMPJ2k="
        - os: android
          language: android
          env: SPEC=android-g++ CONFIG=installer
          sudo: false
          before_install: . travis/android-install.sh
          script: . travis/android-script.sh
          deploy:
            provider: bintray
            file: "bintray/android.json"
            user: "metaxy"
            on:
                branch: master
            key:
                secure: "oavrVI8xdXD1h0xmDMNfQjSlN270glnmQ4gXvN9JocxSkg4KpUPX6fe90xKo+zKVLWtJhncdIzxmSq5VQ1aV/SdJEjasrel6QfvMn3xJVgTh3fQkIgu29QXii0CV9l30TMsrIhjYDkrbGnesulXG/D+QvLdB1xnD/zcsOvZxv3NA/q8gzb8rwPoMrOeWtnzlFUVgm2OKAtYTmyS7GlEnaztXQEsN3l4hViurTV9pFrpS28Ly1IYnOgqahMDHE1YqjRoK+/8+TbmrBQyacZWAXCsD8nnUWKQ364BdGUYZvF653L4a0SRUr1Y5vy0rQktjguhV1duyvcGV42KADAA6lR7C4EaeLDOydA1cuTQaKpmokFIJ6+1L6TtzIqBOjcaNzDGJsvpc8yoaxl0cqx5AKyhRKMvBeuw4nr9y0py4QjBqXmdion547VSD4/coJtMDhtdC8GetO7GkuMwWn2xOwHLdw6X205R+C9D9ePl4gl2CNa7OJUNYZoW7jMhfut08F/rcdeNSW3mNN9Zb2NACZ9+O6vHhzXc92Y0cYNTN32wizbI/+xpLY88aAM4kTpUEVhHzPkDHtCJzTeHTG3BfZuKVedVZjM/sdF9W3zDgkOjtfoyW8+bMJNJ9AKSLQWOWRq/rnVpylPrF9ITForg72W2u0Mh9Gd6/MuvgAlMPJ2k="
        - os: osx
          osx_image: xcode9.2
          env: SPEC=macx-clang CONFIG=installer
          sudo: required
          before_install: . travis/macos-install.sh
          script: . travis/macos-script.sh
          deploy:
            provider: bintray
            file: "bintray/macos.json"
            user: "metaxy"
            on:
                branch: master
            key:
                secure: "oavrVI8xdXD1h0xmDMNfQjSlN270glnmQ4gXvN9JocxSkg4KpUPX6fe90xKo+zKVLWtJhncdIzxmSq5VQ1aV/SdJEjasrel6QfvMn3xJVgTh3fQkIgu29QXii0CV9l30TMsrIhjYDkrbGnesulXG/D+QvLdB1xnD/zcsOvZxv3NA/q8gzb8rwPoMrOeWtnzlFUVgm2OKAtYTmyS7GlEnaztXQEsN3l4hViurTV9pFrpS28Ly1IYnOgqahMDHE1YqjRoK+/8+TbmrBQyacZWAXCsD8nnUWKQ364BdGUYZvF653L4a0SRUr1Y5vy0rQktjguhV1duyvcGV42KADAA6lR7C4EaeLDOydA1cuTQaKpmokFIJ6+1L6TtzIqBOjcaNzDGJsvpc8yoaxl0cqx5AKyhRKMvBeuw4nr9y0py4QjBqXmdion547VSD4/coJtMDhtdC8GetO7GkuMwWn2xOwHLdw6X205R+C9D9ePl4gl2CNa7OJUNYZoW7jMhfut08F/rcdeNSW3mNN9Zb2NACZ9+O6vHhzXc92Y0cYNTN32wizbI/+xpLY88aAM4kTpUEVhHzPkDHtCJzTeHTG3BfZuKVedVZjM/sdF9W3zDgkOjtfoyW8+bMJNJ9AKSLQWOWRq/rnVpylPrF9ITForg72W2u0Mh9Gd6/MuvgAlMPJ2k="
        - os: osx
          osx_image: xcode9.2
          env: SPEC=macx-ios-clang CONFIG=release
          sudo: false
          before_install: . travis/ios-install.sh
          script: . travis/ios-script.sh
          deploy:
            provider: bintray
            file: "bintray/ios.json"
            user: "metaxy"
            on:
                branch: master
            key:
                secure: "oavrVI8xdXD1h0xmDMNfQjSlN270glnmQ4gXvN9JocxSkg4KpUPX6fe90xKo+zKVLWtJhncdIzxmSq5VQ1aV/SdJEjasrel6QfvMn3xJVgTh3fQkIgu29QXii0CV9l30TMsrIhjYDkrbGnesulXG/D+QvLdB1xnD/zcsOvZxv3NA/q8gzb8rwPoMrOeWtnzlFUVgm2OKAtYTmyS7GlEnaztXQEsN3l4hViurTV9pFrpS28Ly1IYnOgqahMDHE1YqjRoK+/8+TbmrBQyacZWAXCsD8nnUWKQ364BdGUYZvF653L4a0SRUr1Y5vy0rQktjguhV1duyvcGV42KADAA6lR7C4EaeLDOydA1cuTQaKpmokFIJ6+1L6TtzIqBOjcaNzDGJsvpc8yoaxl0cqx5AKyhRKMvBeuw4nr9y0py4QjBqXmdion547VSD4/coJtMDhtdC8GetO7GkuMwWn2xOwHLdw6X205R+C9D9ePl4gl2CNa7OJUNYZoW7jMhfut08F/rcdeNSW3mNN9Zb2NACZ9+O6vHhzXc92Y0cYNTN32wizbI/+xpLY88aAM4kTpUEVhHzPkDHtCJzTeHTG3BfZuKVedVZjM/sdF9W3zDgkOjtfoyW8+bMJNJ9AKSLQWOWRq/rnVpylPrF9ITForg72W2u0Mh9Gd6/MuvgAlMPJ2k="


