version: 0.0.{build}
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\livestream-app-generator
configuration: Release

install:
  - set QTDIR=C:\Qt\5.6\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
# scripts to run before build
before_build:
  - cd c:\projects\livestream-app-generator
  
build_script:
- qmake
- dir
- nmake

deploy:
- provider: BinTray
  username: metaxy
  api_key:
    secure: Zp4u4mhL00MlOdQAnVFvg6UsAtLv+h/5VjeJdsedrVp9TpqavUzt91aGo0LL+tvz
  subject: New Build
  repo: livestream-app-generator
  package: Windows
  version: ${version}
  publish: true
  override: true
  explode: true
  artifact: /.*\.exe/
