version: 0.0.{build}
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2013

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\livestream-app-generator
configuration: Release

install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin
# scripts to run before build
before_build:
  - cd c:\projects\livestream-app-generator
  
build_script:
- qmake
- make

deploy:
- provider: BinTray
  username: metaxy
  api_key:
    secure: Zp4u4mhL00MlOdQAnVFvg6UsAtLv+h/5VjeJdsedrVp9TpqavUzt91aGo0LL+tvz
  subject: New Build
  repo: livestream-app-generator
  package: Windows
  version: ${version}
  publish: true
  override: true
  explode: true
  artifact: /.*\.exe/
