version: 0.9.{build}
# branches to build
branches:
  # whitelist
  only:
    - master
environment:
  qt_ver: C:\Qt\5.9.2\winrt_x64_msvc2017


# Operating system (build VM template)
os: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\livestream-app-generator
configuration: Release

# scripts to run before build
before_build:
  - cd c:\projects\ivestream-app-generator
  
build_script:
- qmake
- make

deploy:
- provider: BinTray
  username: metaxy
  api_key:
    secure: Zp4u4mhL00MlOdQAnVFvg6UsAtLv+h/5VjeJdsedrVp9TpqavUzt91aGo0LL+tvz
  subject: johnsmith
  repo: livestream-app-generator
  package: Windows
  version: ${version}
  publish: true
  override: true
  explode: true
  artifact: /.*\.exe/
